# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-30 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courriers_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='mail',
            field=models.ImageField(null=True, upload_to=b''),
        ),
    ]
