# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-30 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courriers_app', '0002_auto_20180730_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='number',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
