# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-31 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courriers_app', '0004_mail_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='closed_time',
            field=models.DateTimeField(null=True),
        ),
    ]
