# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-12-22 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courriers_app', '0005_mail_closed_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='answered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mail',
            name='external_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mail',
            name='need_answer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mail',
            name='recorded_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='hard_copy_transfer_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='mail',
            name='number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='mail',
            name='received_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
