# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-12-25 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courriers_app', '0006_auto_20191222_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='upload',
            field=models.FileField(null=True, upload_to='uploads/% Y/% m/% d/'),
        ),
    ]
