# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-12-25 20:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courriers_app', '0007_mail_upload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mail',
            old_name='upload',
            new_name='soft_copy',
        ),
    ]
