# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2020-01-14 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courriers_app', '0012_auto_20200113_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sender',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sender',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sender',
            name='phone_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
