# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2020-01-19 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courriers_app', '0013_auto_20200114_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='soft_copy',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
