# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2020-01-20 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courriers_app', '0014_auto_20200119_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='soft_copy',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
