# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2021-05-24 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courriers_app', '0015_track_soft_copy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_name', models.CharField(max_length=200)),
                ('setting_value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TimeMeasuringUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4)),
                ('description', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='settings',
            name='time_measuring_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courriers_app.TimeMeasuringUnit'),
        ),
    ]
