# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2021-05-27 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courriers_app', '0016_auto_20210524_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
