# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2021-09-05 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courriers_app', '0017_staff_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='closure_reason',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='purpose',
            field=models.CharField(max_length=300),
        ),
    ]
